---
title: "In-class_Ex03"
date: "25 Jan 2023"
date-modified: "`r Sys.Date()`"
number-sections: true
format: html
execute: 
  echo: true
  eval: true
  message: true
  warning: false
editor: visual
---

```{r}
pacman::p_load(sf, tmap, tidyverse)
```

##Importing Data

```{r}
NGA_wp <- read_rds("data/rds/NGA_wp.rds")
```

```{r}
p1 <- tm_shape(NGA_wp) +
  tm_fill("wp_functional", 
          n=10,
          style="equal",
          palette = "Blues") + 
  tm_borders(lwd=0.1, 
             alpha = 1) + 
  tm_layout(main.title = "Distribution of funtional water points",
            legend.outside = FALSE)
p1
```

```{r}
#tmap_arrange(p2, p1, nrow=1)
```

```{r}
NGA_wp <- NGA_wp %>%
  mutate(pct_functional = wp_functional/total_wp) %>%
  mutate(pct_nonfunctional = wp_nonfunctional/total_wp)
```

```{r}
tm_shape(NGA_wp) +
  tm_fill("wp_functional", 
          n=10,
          style="equal",
          palette = "Blues",
          legend.hist = TRUE) + 
  tm_borders(lwd=0.1, 
             alpha = 1) + 
  tm_layout(main.title = "Rate map of functional water point",
            legend.outside = TRUE)

```

#Percentile Map #step 1; exclude records with NA

```{r}
NGA_wp <- NGA_wp %>%
  drop_na()
```

#step 2 creating customised classification and extracting values

```{r}
percent <- c(0, .01, .1, .5, .9, .99, 1)
var <- NGA_wp["pct_functional"] %>%
  st_set_geometry(NULL)
quantile(var[,1], percent)
```

```{r}
get.var <- function(vname, df){
  v <- df[vname] %>%
    st_set_geometry(NULL)
  v <- unname(v[,1])
  return(v)
}
```

```{r}
percentmap <- function(vname, df, legtitle=NA, mtitle="Percentile Map"){
  percent <- c(0, .01, .1, .5, .9, .99, 1)
  var <- get.var(vname, df)
  bperc <- quantile(var, percent)
  tm_shape(df) + 
  tm_polygons() + 
  tm_shape(df) + 
    tm_fill(
      vname,
      title = legtitle,
      breaks = bperc,
      palette = "Blues",
      labels = c("< 1%", "1% - 10%", "10% - 50%", "50% - 90%", "90% - 99%", "99% - 100%")
    ) + 
    tm_borders()+ 
    tm_layout(main.title = mtitle,
              title.position = c("right", "bottom"))
}

  
```

```{r}
percentmap("pct_functional", NGA_wp)
```
